// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RequestAndDelivery.Data;

#nullable disable

namespace RequestAndDelivery.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231212095912_editTables")]
    partial class editTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RequestAndDelivery.Data.Domain_Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Branchs");
                });

            modelBuilder.Entity("RequestAndDelivery.Data.Domain_Models.BranchDepartment", b =>
                {
                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.HasKey("BranchId", "DepartmentId");

                    b.HasIndex("BranchId")
                        .IsUnique();

                    b.HasIndex("DepartmentId")
                        .IsUnique();

                    b.ToTable("BranchDepartments");
                });

            modelBuilder.Entity("RequestAndDelivery.Data.Domain_Models.Delivary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DelivaryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("DeviceSerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceSerialNumber");

                    b.HasIndex("RequestId");

                    b.ToTable("Delivaries");
                });

            modelBuilder.Entity("RequestAndDelivery.Data.Domain_Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("RequestAndDelivery.Data.Domain_Models.Device", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeDeliverFromId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeDeliverToId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SerialNumber");

                    b.HasIndex("EmployeeDeliverFromId");

                    b.HasIndex("EmployeeDeliverToId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("RequestAndDelivery.Data.Domain_Models.DeviceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeviceTypes");
                });

            modelBuilder.Entity("RequestAndDelivery.Data.Domain_Models.Employee", b =>
                {
                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MobileNumber");

                    b.HasIndex("BranchId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("RequestAndDelivery.Data.Domain_Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DeviceTypeId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExportNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeliverd")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceTypeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("RequestAndDelivery.Data.Domain_Models.BranchDepartment", b =>
                {
                    b.HasOne("RequestAndDelivery.Data.Domain_Models.Branch", "Branch")
                        .WithOne("Departments")
                        .HasForeignKey("RequestAndDelivery.Data.Domain_Models.BranchDepartment", "BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RequestAndDelivery.Data.Domain_Models.Department", "Department")
                        .WithOne("Branchs")
                        .HasForeignKey("RequestAndDelivery.Data.Domain_Models.BranchDepartment", "DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("RequestAndDelivery.Data.Domain_Models.Delivary", b =>
                {
                    b.HasOne("RequestAndDelivery.Data.Domain_Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceSerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RequestAndDelivery.Data.Domain_Models.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("RequestAndDelivery.Data.Domain_Models.Device", b =>
                {
                    b.HasOne("RequestAndDelivery.Data.Domain_Models.Employee", "EmployeeDeliverFrom")
                        .WithMany()
                        .HasForeignKey("EmployeeDeliverFromId");

                    b.HasOne("RequestAndDelivery.Data.Domain_Models.Employee", "EmployeeDeliverTo")
                        .WithMany()
                        .HasForeignKey("EmployeeDeliverToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeDeliverFrom");

                    b.Navigation("EmployeeDeliverTo");
                });

            modelBuilder.Entity("RequestAndDelivery.Data.Domain_Models.Employee", b =>
                {
                    b.HasOne("RequestAndDelivery.Data.Domain_Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RequestAndDelivery.Data.Domain_Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("RequestAndDelivery.Data.Domain_Models.Request", b =>
                {
                    b.HasOne("RequestAndDelivery.Data.Domain_Models.DeviceType", "DeviceType")
                        .WithMany("Requests")
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RequestAndDelivery.Data.Domain_Models.Employee", "Employee")
                        .WithMany("Requests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceType");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("RequestAndDelivery.Data.Domain_Models.Branch", b =>
                {
                    b.Navigation("Departments")
                        .IsRequired();
                });

            modelBuilder.Entity("RequestAndDelivery.Data.Domain_Models.Department", b =>
                {
                    b.Navigation("Branchs")
                        .IsRequired();
                });

            modelBuilder.Entity("RequestAndDelivery.Data.Domain_Models.DeviceType", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("RequestAndDelivery.Data.Domain_Models.Employee", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
